import { Megaphone, PlusCircle, RefreshCw, SearchX } from "lucide-react";

export function AnnouncementSkeleton() {
  return <div aria-busy="true" aria-label="Loading announcements" className="space-y-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{Array.from({ length: 4 }, (_, index) => <div key={index} className="h-32 animate-pulse rounded-2xl border border-slate-200 bg-white p-5 dark:border-[#1C2940] dark:bg-[#0B1220]"><div className="size-12 rounded-full bg-slate-200 dark:bg-slate-700" /><div className="ml-16 -mt-10 h-4 w-28 rounded bg-slate-200 dark:bg-slate-700" /><div className="ml-16 mt-2 h-7 w-10 rounded bg-slate-200 dark:bg-slate-700" /></div>)}</div><div className="h-28 animate-pulse rounded-2xl border border-slate-200 bg-white dark:border-[#1C2940] dark:bg-[#0B1220]" /><div className="grid gap-5 xl:grid-cols-[minmax(0,1.55fr)_minmax(340px,0.9fr)]"><div className="h-96 animate-pulse rounded-2xl border border-slate-200 bg-white dark:border-[#1C2940] dark:bg-[#0B1220]" /><div className="h-96 animate-pulse rounded-2xl border border-slate-200 bg-white dark:border-[#1C2940] dark:bg-[#0B1220]" /></div></div>;
}

export function AnnouncementsEmptyState({ filtered, onCreate, onBrowse, onClear }: { filtered: boolean; onCreate: () => void; onBrowse: () => void; onClear: () => void }) {
  return <div className="flex min-h-[390px] flex-col items-center justify-center rounded-2xl border border-slate-200 bg-white px-6 py-12 text-center shadow-sm dark:border-[#1C2940] dark:bg-[#0B1220]"><span className="relative grid size-28 place-items-center rounded-full bg-red-50 text-red-600 dark:bg-red-500/15 dark:text-red-300">{filtered ? <SearchX size={45} /> : <Megaphone size={48} />}<span className="absolute -right-1 top-2 size-3 rounded-full bg-red-200" /><span className="absolute -left-2 bottom-5 size-2 rounded-full bg-red-300" /></span><h2 className="mt-6 text-xl font-black text-slate-950 dark:text-white">{filtered ? "No matching announcements" : "No announcements yet"}</h2><p className="mt-2 max-w-md text-sm leading-6 text-slate-500 dark:text-slate-400">{filtered ? "Try adjusting the status, audience, or search filters." : "Create your first announcement to inform volunteers, responders, and community members."}</p><div className="mt-6 flex flex-col gap-2 sm:flex-row">{filtered ? <button type="button" onClick={onClear} className="h-11 rounded-xl bg-red-600 px-5 text-sm font-bold text-white hover:bg-red-700">Clear Filters</button> : <button type="button" onClick={onCreate} className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-red-600 px-5 text-sm font-bold text-white hover:bg-red-700"><PlusCircle size={17} /> Create Announcement</button>}<button type="button" onClick={onBrowse} className="h-11 rounded-xl px-5 text-sm font-bold text-slate-600 hover:bg-slate-50 dark:text-slate-300 dark:hover:bg-[#122036]">Browse Templates</button></div></div>;
}

export function AnnouncementErrorState({ onRetry }: { onRetry: () => void }) {
  return <div role="alert" className="flex min-h-72 flex-col items-center justify-center rounded-2xl border border-red-200 bg-red-50 px-6 text-center dark:border-red-500/25 dark:bg-red-500/10"><span className="grid size-12 place-items-center rounded-full bg-white text-red-600 shadow-sm dark:bg-[#0B1220] dark:text-red-300"><RefreshCw size={22} /></span><h2 className="mt-4 font-black text-red-900 dark:text-red-100">We couldn’t load announcements</h2><p className="mt-1 text-sm text-red-700 dark:text-red-200">Please check your connection and try again.</p><button type="button" onClick={onRetry} className="mt-5 h-10 rounded-xl bg-red-600 px-4 text-sm font-bold text-white hover:bg-red-700">Retry</button></div>;
}
