import { Ionicons } from "@expo/vector-icons";
import { StyleSheet, Text, View } from "react-native";
import type { TrackingLabel } from "../../models/myRequests";

type Props = { title: string; status: string; trackingLabel: TrackingLabel; location: string; statusMessage: string; priority?: string | null; referenceNumber: string; incidentType: string; reportedAt: string; lastUpdated: string; notes?: string; rejectionReason?: string };
function colors(label: TrackingLabel) { if (label === "Resolved") return { bg: "#DCFCE7", border: "#86EFAC", text: "#166534" }; if (label === "En Route" || label === "Arrived") return { bg: "#FEF3C7", border: "#FCD34D", text: "#92400E" }; if (label === "Cancelled") return { bg: "#FEE2E2", border: "#FCA5A5", text: "#991B1B" }; return { bg: "#EEF2FF", border: "#C7D2FE", text: "#4338CA" }; }

export function EmergencyDetailsCard(p: Props) { const tone = colors(p.trackingLabel); return <View style={styles.card}><View style={styles.heading}><View style={styles.icon}><Ionicons name="warning" size={24} color="#FFF" /></View><Text style={styles.title} numberOfLines={2}>{p.title}</Text><View style={[styles.badge, { backgroundColor: tone.bg, borderColor: tone.border }]}><Text style={[styles.badgeText, { color: tone.text }]}>{p.status}</Text></View></View><View style={styles.locationRow}><Ionicons name="location-outline" size={20} color="#64748B" /><Text style={styles.location}>{p.location}</Text></View><View style={styles.statusRow}><Ionicons name={p.trackingLabel === "Resolved" ? "checkmark-circle-outline" : "time-outline"} size={20} color={p.trackingLabel === "Resolved" ? "#16A34A" : "#DC2626"} /><Text style={[styles.status, p.trackingLabel === "Resolved" && { color: "#16A34A" }]} numberOfLines={2}>{p.statusMessage}</Text>{p.priority?.trim() ? <View style={styles.priority}><Text style={styles.priorityText}>{p.priority} Priority</Text></View> : null}</View>{p.rejectionReason ? <View style={styles.reason}><Text style={styles.reasonTitle}>Reason from LGU</Text><Text style={styles.reasonText}>{p.rejectionReason}</Text></View> : null}{p.notes ? <Text style={styles.notes} numberOfLines={3}>{p.notes}</Text> : null}<View style={styles.divider} /><View style={styles.grid}><Detail label="Reference ID" value={p.referenceNumber || "—"} /><View style={styles.detail}><Text style={styles.detailLabel}>Incident Type</Text><View style={styles.type}><Ionicons name="pulse" size={14} color="#DC2626" /><Text style={styles.typeText}>{p.incidentType}</Text></View></View><Detail label="Reported" value={p.reportedAt} /><View style={styles.detail}><Text style={styles.detailLabel}>Last Update</Text><Text style={styles.updated}>{p.lastUpdated}</Text></View></View></View>; }
function Detail({ label, value }: { label: string; value: string }) { return <View style={styles.detail}><Text style={styles.detailLabel}>{label}</Text><Text style={styles.detailValue}>{value}</Text></View>; }
const styles = StyleSheet.create({ card: { marginHorizontal: 16, borderRadius: 22, borderWidth: 1, borderColor: "#E2E8F0", backgroundColor: "#FFF", padding: 16, shadowColor: "#0F172A", shadowOpacity: 0.05, shadowRadius: 12, elevation: 2 }, heading: { flexDirection: "row", alignItems: "center", gap: 10 }, icon: { width: 48, height: 48, borderRadius: 24, alignItems: "center", justifyContent: "center", backgroundColor: "#DC2626" }, title: { flex: 1, fontSize: 21, lineHeight: 26, fontWeight: "900", color: "#0F172A" }, badge: { alignSelf: "flex-start", borderRadius: 999, borderWidth: 1, paddingHorizontal: 10, paddingVertical: 4 }, badgeText: { fontSize: 11, fontWeight: "900" }, locationRow: { marginTop: 13, marginLeft: 56, flexDirection: "row", alignItems: "flex-start", gap: 7 }, location: { flex: 1, fontSize: 14, lineHeight: 20, fontWeight: "600", color: "#64748B" }, statusRow: { marginTop: 14, flexDirection: "row", alignItems: "center", gap: 8 }, status: { flex: 1, fontSize: 14, fontWeight: "900", color: "#DC2626" }, priority: { borderRadius: 999, backgroundColor: "#FEE2E2", paddingHorizontal: 10, paddingVertical: 5 }, priorityText: { fontSize: 11, fontWeight: "800", color: "#B91C1C", textTransform: "capitalize" }, reason: { marginTop: 12, borderRadius: 12, borderWidth: 1, borderColor: "#FECACA", backgroundColor: "#FEF2F2", padding: 11 }, reasonTitle: { fontSize: 11, fontWeight: "900", color: "#991B1B" }, reasonText: { marginTop: 3, fontSize: 12, lineHeight: 17, fontWeight: "600", color: "#7F1D1D" }, notes: { marginTop: 12, fontSize: 13, lineHeight: 19, color: "#64748B" }, divider: { height: 1, marginVertical: 15, backgroundColor: "#E2E8F0" }, grid: { flexDirection: "row", flexWrap: "wrap", rowGap: 16 }, detail: { width: "50%", paddingRight: 8 }, detailLabel: { fontSize: 12, fontWeight: "600", color: "#64748B" }, detailValue: { marginTop: 4, fontSize: 13, lineHeight: 18, fontWeight: "800", color: "#0F172A" }, updated: { marginTop: 4, fontSize: 13, fontWeight: "900", color: "#DC2626" }, type: { alignSelf: "flex-start", marginTop: 4, flexDirection: "row", alignItems: "center", gap: 4, borderRadius: 8, backgroundColor: "#FEF2F2", paddingHorizontal: 8, paddingVertical: 4 }, typeText: { fontSize: 11, fontWeight: "800", color: "#B91C1C" } });
