import { Ionicons } from "@expo/vector-icons";
import { Image, Pressable, StyleSheet, Text, View } from "react-native";
import type { MyRequestTrackingDTO, TrackingLabel } from "../../models/myRequests";
import { responderInitials } from "../utils/tracking.utils";
type Responder = NonNullable<MyRequestTrackingDTO["tracking"]["responder"]>;

export function ResponderStatusCard({ responder, trackingLabel, etaText, onCall }: { responder?: Responder; trackingLabel: TrackingLabel; etaText: string; onCall?: () => void }) {
  const waiting = !responder; const name = responder?.name?.trim() || (trackingLabel === "Resolved" ? "Response completed" : trackingLabel === "Cancelled" ? "No active responder" : "Waiting for responder"); const id = responder?.lifelineId?.trim() || (waiting ? "Waiting for assignment" : "ID unavailable");
  return <View style={[styles.card, waiting && styles.waitingCard]}><View style={styles.avatar}>{responder?.avatarUrl ? <Image source={{ uri: responder.avatarUrl }} style={styles.avatarImage} /> : waiting ? <Ionicons name="person" size={27} color="#DC2626" /> : <Text style={styles.initials}>{responderInitials(responder.name)}</Text>}</View><View style={styles.content}><Text style={styles.label}>Your Responder</Text><Text style={styles.name} numberOfLines={1}>{name}</Text><Text style={styles.meta} numberOfLines={1}>{waiting ? `Lifeline ID: ${id}` : responder?.role?.trim() || "Emergency Responder"}</Text>{responder ? <Text style={styles.responderId} numberOfLines={1}>Lifeline ID: {id} · {trackingLabel}</Text> : null}{!waiting && trackingLabel === "En Route" ? <Text style={styles.eta}>{etaText}</Text> : null}</View>{onCall ? <Pressable onPress={onCall} style={styles.callButton} accessibilityLabel="Call responder"><Ionicons name="call-outline" size={21} color="#DC2626" /></Pressable> : <View style={styles.statusIcon}><Ionicons name={waiting ? "pulse" : "shield-checkmark-outline"} size={21} color={waiting ? "#DC2626" : "#16A34A"} /></View>}</View>;
}
const styles = StyleSheet.create({ card: { marginHorizontal: 16, borderRadius: 20, borderWidth: 1, borderColor: "#E2E8F0", backgroundColor: "#FFFFFF", padding: 15, flexDirection: "row", alignItems: "center", shadowColor: "#0F172A", shadowOpacity: 0.05, shadowRadius: 10, elevation: 2 }, waitingCard: { borderColor: "#FECACA", backgroundColor: "#FFF8F8" }, avatar: { width: 58, height: 58, overflow: "hidden", borderRadius: 29, alignItems: "center", justifyContent: "center", backgroundColor: "#FEE2E2", borderWidth: 1, borderColor: "#FECACA" }, avatarImage: { width: "100%", height: "100%" }, initials: { fontSize: 17, fontWeight: "900", color: "#991B1B" }, content: { flex: 1, marginHorizontal: 14 }, label: { fontSize: 12, fontWeight: "700", color: "#64748B" }, name: { marginTop: 2, fontSize: 18, fontWeight: "900", color: "#0F172A" }, meta: { marginTop: 3, fontSize: 13, fontWeight: "600", color: "#64748B" }, responderId: { marginTop: 2, fontSize: 11, fontWeight: "700", color: "#16A34A" }, eta: { marginTop: 4, fontSize: 12, fontWeight: "800", color: "#D97706" }, statusIcon: { width: 42, height: 42, borderRadius: 13, alignItems: "center", justifyContent: "center", backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#FECACA" }, callButton: { width: 44, height: 44, borderRadius: 14, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: "#FECACA", backgroundColor: "#FFFFFF" } });
