export const AUDIT_SEVERITY = {
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
  CRITICAL: "CRITICAL",
} as const;

export const AUDIT_OUTCOME = {
  SUCCESS: "SUCCESS",
  FAIL: "FAIL",
  DENY: "DENY",
} as const;

export const AUDIT_EVENT = {
  AUTH_LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
  AUTH_LOGIN_FAIL: "AUTH_LOGIN_FAIL",
  AUTH_LOGOUT: "AUTH_LOGOUT",
  AUTH_PASSWORD_RESET_REQUEST: "AUTH_PASSWORD_RESET_REQUEST",
  AUTH_PASSWORD_RESET_SUCCESS: "AUTH_PASSWORD_RESET_SUCCESS",
  AUTH_MFA_CHALLENGE_SENT: "AUTH_MFA_CHALLENGE_SENT",
  AUTH_MFA_VERIFY_SUCCESS: "AUTH_MFA_VERIFY_SUCCESS",
  AUTH_MFA_VERIFY_FAIL: "AUTH_MFA_VERIFY_FAIL",
  AUTH_OAUTH_GOOGLE_SUCCESS: "AUTH_OAUTH_GOOGLE_SUCCESS",
  AUTH_OAUTH_GOOGLE_FAIL: "AUTH_OAUTH_GOOGLE_FAIL",

  SECURITY_CSRF_FAIL: "SECURITY_CSRF_FAIL",
  SECURITY_RATE_LIMIT_HIT: "SECURITY_RATE_LIMIT_HIT",
  SECURITY_ACCESS_DENIED: "SECURITY_ACCESS_DENIED",

  DISPATCH_CREATE: "DISPATCH_CREATE",
  DISPATCH_UPDATE: "DISPATCH_UPDATE",
  DISPATCH_STATUS_CHANGE: "DISPATCH_STATUS_CHANGE",
  EMERGENCY_REPORT_APPROVAL: "EMERGENCY_REPORT_APPROVAL",

  HAZARDZONE_CREATE: "HAZARDZONE_CREATE",
  HAZARDZONE_UPDATE: "HAZARDZONE_UPDATE",
  HAZARDZONE_DELETE: "HAZARDZONE_DELETE",

  VOLUNTEER_APPLICATION_CREATE: "VOLUNTEER_APPLICATION_CREATE",
  VOLUNTEER_APPLICATION_REVIEW: "VOLUNTEER_APPLICATION_REVIEW",
  VOLUNTEER_APPLICATION_APPROVE: "VOLUNTEER_APPLICATION_APPROVE",
  VOLUNTEER_APPLICATION_REJECT: "VOLUNTEER_APPLICATION_REJECT",

  ADMIN_ROLE_CHANGE: "ADMIN_ROLE_CHANGE",
  ADMIN_ACCOUNT_CREATE: "ADMIN_ACCOUNT_CREATE",
  ADMIN_ACCOUNT_DISABLE: "ADMIN_ACCOUNT_DISABLE",
  ADMIN_ACCOUNT_ENABLE: "ADMIN_ACCOUNT_ENABLE",
} as const;

export type AuditSeverity = (typeof AUDIT_SEVERITY)[keyof typeof AUDIT_SEVERITY];
export type AuditOutcome = (typeof AUDIT_OUTCOME)[keyof typeof AUDIT_OUTCOME];
export type AuditEventType = (typeof AUDIT_EVENT)[keyof typeof AUDIT_EVENT];

export const AUDIT_EVENT_SEVERITY: Record<AuditEventType, AuditSeverity> = {
  AUTH_LOGIN_SUCCESS: AUDIT_SEVERITY.LOW,
  AUTH_LOGIN_FAIL: AUDIT_SEVERITY.MEDIUM,
  AUTH_LOGOUT: AUDIT_SEVERITY.LOW,
  AUTH_PASSWORD_RESET_REQUEST: AUDIT_SEVERITY.MEDIUM,
  AUTH_PASSWORD_RESET_SUCCESS: AUDIT_SEVERITY.HIGH,
  AUTH_MFA_CHALLENGE_SENT: AUDIT_SEVERITY.MEDIUM,
  AUTH_MFA_VERIFY_SUCCESS: AUDIT_SEVERITY.MEDIUM,
  AUTH_MFA_VERIFY_FAIL: AUDIT_SEVERITY.HIGH,
  AUTH_OAUTH_GOOGLE_SUCCESS: AUDIT_SEVERITY.LOW,
  AUTH_OAUTH_GOOGLE_FAIL: AUDIT_SEVERITY.MEDIUM,

  SECURITY_CSRF_FAIL: AUDIT_SEVERITY.HIGH,
  SECURITY_RATE_LIMIT_HIT: AUDIT_SEVERITY.MEDIUM,
  SECURITY_ACCESS_DENIED: AUDIT_SEVERITY.HIGH,

  DISPATCH_CREATE: AUDIT_SEVERITY.MEDIUM,
  DISPATCH_UPDATE: AUDIT_SEVERITY.MEDIUM,
  DISPATCH_STATUS_CHANGE: AUDIT_SEVERITY.MEDIUM,
  EMERGENCY_REPORT_APPROVAL: AUDIT_SEVERITY.MEDIUM,

  HAZARDZONE_CREATE: AUDIT_SEVERITY.MEDIUM,
  HAZARDZONE_UPDATE: AUDIT_SEVERITY.MEDIUM,
  HAZARDZONE_DELETE: AUDIT_SEVERITY.HIGH,

  VOLUNTEER_APPLICATION_CREATE: AUDIT_SEVERITY.LOW,
  VOLUNTEER_APPLICATION_REVIEW: AUDIT_SEVERITY.MEDIUM,
  VOLUNTEER_APPLICATION_APPROVE: AUDIT_SEVERITY.MEDIUM,
  VOLUNTEER_APPLICATION_REJECT: AUDIT_SEVERITY.MEDIUM,

  ADMIN_ROLE_CHANGE: AUDIT_SEVERITY.CRITICAL,
  ADMIN_ACCOUNT_CREATE: AUDIT_SEVERITY.HIGH,
  ADMIN_ACCOUNT_DISABLE: AUDIT_SEVERITY.HIGH,
  ADMIN_ACCOUNT_ENABLE: AUDIT_SEVERITY.HIGH,
};
