import type { ImageSource } from "expo-image";
import type { AchievementId } from "../models/achievement.types";

export const ACHIEVEMENT_BADGE_ASSETS: Record<AchievementId, ImageSource> = {
  "verified-volunteer": require("../../../assets/images/badges/verified-volunteer.png"),
  "ready-to-respond": require("../../../assets/images/badges/ready-to-respond.png"),
  "first-response": require("../../../assets/images/badges/first-response.png"),
  "helping-hand": require("../../../assets/images/badges/helping-hand.png"),
  "community-responder": require("../../../assets/images/badges/community-responder.png"),
  "dedicated-responder": require("../../../assets/images/badges/dedicated-responder.png"),
  "lifeline-guardian": require("../../../assets/images/badges/lifeline-guardian.png"),
  "community-protector": require("../../../assets/images/badges/community-protector.png"),
  "response-veteran": require("../../../assets/images/badges/response-veteran.png"),
  "trusted-responder": require("../../../assets/images/badges/trusted-responder.png"),
  "dependable-hand": require("../../../assets/images/badges/dependable-hand.png"),
  "always-ready": require("../../../assets/images/badges/always-ready.png"),
  "trusted-lifeline": require("../../../assets/images/badges/trusted-lifeline.png"),
  "response-certified": require("../../../assets/images/badges/response-certified.png"),
  "chain-of-trust": require("../../../assets/images/badges/chain-of-trust.png"),
  "immutable-impact": require("../../../assets/images/badges/immutable-impact.png"),
  "team-player": require("../../../assets/images/badges/team-player.png"),
  "helping-together": require("../../../assets/images/badges/helping-together.png"),
  "community-connector": require("../../../assets/images/badges/community-connector.png"),
  "response-partner": require("../../../assets/images/badges/response-partner.png"),
  "united-we-respond": require("../../../assets/images/badges/united-we-respond.png"),
  "response-leader": require("../../../assets/images/badges/response-leader.png"),
  "first-step": require("../../../assets/images/badges/first-step.png"),
  "getting-started": require("../../../assets/images/badges/getting-started.png"),
  "making-a-difference": require("../../../assets/images/badges/making-a-difference.png"),
  "service-starter": require("../../../assets/images/badges/service-starter.png"),
  "community-supporter": require("../../../assets/images/badges/community-supporter.png"),
  "service-champion": require("../../../assets/images/badges/service-champion.png"),
  "community-guardian": require("../../../assets/images/badges/community-guardian.png"),
  "lifeline-veteran": require("../../../assets/images/badges/lifeline-veteran.png"),
  "legacy-responder": require("../../../assets/images/badges/legacy-responder.png"),
  "medical-aid-responder": require("../../../assets/images/badges/medical-aid-responder.png"),
  "flood-response-ready": require("../../../assets/images/badges/flood-response-ready.png"),
  "fire-response-ready": require("../../../assets/images/badges/fire-response-ready.png"),
  "rescue-ready": require("../../../assets/images/badges/rescue-ready.png"),
  "evacuation-supporter": require("../../../assets/images/badges/evacuation-supporter.png"),
  "relief-coordinator": require("../../../assets/images/badges/relief-coordinator.png"),
  "navigation-specialist": require("../../../assets/images/badges/navigation-specialist.png"),
  "field-support-specialist": require("../../../assets/images/badges/field-support-specialist.png"),
  "community-ready": require("../../../assets/images/badges/community-ready.png"),
  "safety-aware": require("../../../assets/images/badges/safety-aware.png"),
  "verified-reporter": require("../../../assets/images/badges/verified-reporter.png"),
  "community-watch": require("../../../assets/images/badges/community-watch.png"),
  "prepared-citizen": require("../../../assets/images/badges/prepared-citizen.png"),
  "lifeline-supporter": require("../../../assets/images/badges/lifeline-supporter.png"),
  "heart-of-lifeline": require("../../../assets/images/badges/heart-of-lifeline.png"),
  "guardian-of-the-community": require("../../../assets/images/badges/guardian-of-the-community.png"),
  "beacon-of-hope": require("../../../assets/images/badges/beacon-of-hope.png"),
  "above-and-beyond": require("../../../assets/images/badges/above-and-beyond.png"),
  "pillar-of-service": require("../../../assets/images/badges/pillar-of-service.png"),
};
